ERROR Internal Server Error: /
Traceback (most recent call last):
  File "/home/beatpanda/.virtualenvs/lopa/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/beatpanda/.virtualenvs/lopa/local/lib/python2.7/site-packages/django/middleware/common.py", line 57, in process_request
    host = request.get_host()
  File "/home/beatpanda/.virtualenvs/lopa/local/lib/python2.7/site-packages/django/http/request.py", line 72, in get_host
    "Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): %s" % host)
SuspiciousOperation: Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): localhost:8000
ERROR Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/beatpanda/.virtualenvs/lopa/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/beatpanda/.virtualenvs/lopa/local/lib/python2.7/site-packages/django/middleware/common.py", line 57, in process_request
    host = request.get_host()
  File "/home/beatpanda/.virtualenvs/lopa/local/lib/python2.7/site-packages/django/http/request.py", line 72, in get_host
    "Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): %s" % host)
SuspiciousOperation: Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): localhost:8000
